globus/globus-jupyterlab

globus_jupyterlab/globus_config.py
globus_jupyterlab/handlers/__init__.py
globus_jupyterlab/handlers/api/__init__.py
globus_jupyterlab/handlers/api/transfer.py
globus_jupyterlab/handlers/base.py
globus_jupyterlab/handlers/config.py
globus_jupyterlab/handlers/login.py
globus_jupyterlab/login_manager.py
globus_jupyterlab/models.py
globus_jupyterlab/tests/__init__.py
globus_jupyterlab/tests/test_setup.py
src/index.ts

Changes to support Globus Auth.
Progress: 
[Shortcut](https://app.shortcut.com/globus/story/13605/server-extension-log-into-globus-using-native-app-flow)

Server extension globus auth

---

.github/workflows/docker.yml
Dockerfile
MANIFEST.in
README.md
docs/setups/local_setup.md
globus_jupyterlab/globus_config.py
jupyter-config/nb-config/globus_jupyterlab.json
jupyter-config/server-config/globus_jupyterlab.json
setup.py

Updates docs and fixes Dockerfile
The dockerfile isn't quite running correctly, so this is marked WIP for now.

Packaging fixes

---

globus_jupyterlab/__init__.py
globus_jupyterlab/exc.py
globus_jupyterlab/globus_config.py
globus_jupyterlab/handlers/api/transfer.py
globus_jupyterlab/handlers/login.py
globus_jupyterlab/login_manager.py
globus_jupyterlab/models.py
globus_jupyterlab/tests/integration/mini_resource_server.py
src/components/Endpoint.tsx

Support JupyterLab configuring custom resource servers for delegating transfer submission.

Custom resource server

---

MANIFEST.in
src/components/Endpoint.tsx

Added a couple last minute fixes to packaging and transfer document schema.

Packaging fixes and schema fix

---

.github/workflows/docker.yml

This was mistakenly removed in an older commit

chore: Re add docker builds

---

docs/gcp.rst
docs/index.rst
docs/installation.rst
docs/jupyterhub.rst

Consider deleting the GCP section.   I added that text to the JupyterHub section.
I couldn't find the Config Reference doc in the repo.  What am I missing?

Documentation Review

---

docs/config.rst
globus_jupyterlab/globus_config.py
globus_jupyterlab/handlers/config.py
globus_jupyterlab/tests/conftest.py
globus_jupyterlab/tests/test_config_handler.py
globus_jupyterlab/tests/test_globus_config.py

Allow collections to be configured on the env. 
Additionally added some tweaks to docs

feat: Make Globus Collection ID/path configurable

---

CHANGELOG.md
docs/CHANGELOG.rst
docs/conf.py
docs/index.rst
docs/requirements.txt
package.json

Add a changelog to track changes between releases. Changelog generated using (via standard-version): 
https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli

Add changelog

---

globus_jupyterlab/tests/api/test_transfer.py
globus_jupyterlab/tests/conftest.py
globus_jupyterlab/tests/mocks.py
globus_jupyterlab/tests/test_config_handler.py
globus_jupyterlab/tests/test_globus_config.py

Coverage is up from 4% to 75%, but there are still plenty more to add.

Add Transfer unit tests

---

globus_jupyterlab/handlers/api/transfer.py
src/components/Endpoint.tsx
src/components/EndpointSearch.tsx
src/components/Endpoints.tsx
src/components/HubLoginWidget.tsx
src/handler.ts
src/index.ts
src/widget.tsx

This should be everything in https://app.shortcut.com/globus/story/15123/front-end-improvements. Always open for suggestions! :)

Front-end improvements, UI updates, code refactoring

---

globus_jupyterlab/globus_config.py
globus_jupyterlab/handlers/api/transfer.py
globus_jupyterlab/login_manager.py
globus_jupyterlab/tests/api/test_transfer.py
globus_jupyterlab/tests/conftest.py
globus_jupyterlab/tests/test_config_handler.py
globus_jupyterlab/tests/test_login_manager.py

Add a couple different fixes, one for expired tokens and another in exception handling when dealing with 401/403 responses. Also improve and add more unit tests.

Auth token fixes

---

globus_jupyterlab/exc.py
globus_jupyterlab/handlers/api/transfer.py
globus_jupyterlab/handlers/login.py
globus_jupyterlab/tests/api/test_transfer.py

Catch GCS Error on missing session and log the user in with the required identities. 
**Note** Marked draft for being dependent on #66

GCS v5.4 HA Support

---

globus_jupyterlab/globus_config.py
globus_jupyterlab/handlers/config.py
globus_jupyterlab/handlers/login.py

Config will now return last_login for last successful user auth.

Internal server-extension feature to track last user login.

---

.pre-commit-config.yaml
src/components/Endpoint.tsx
src/components/GlobusObjects.ts
src/components/HubLoginWidget.tsx
src/index.ts
src/widget.tsx
tsconfig.json

Just going to get this in for review. Needs a bunch of testing :) 
Hopefully will mostly take care of:
https://app.shortcut.com/globus/story/15821
https://app.shortcut.com/globus/story/15820
https://app.shortcut.com/globus/story/15819
https://app.shortcut.com/globus/story/15859

Fix directory transfer error

---

docs/jupyterhub.rst

docs: fix incorrect value for collection id in docs

---

docs/jupyterhub.rst
globus_jupyterlab/globus_config.py

An additional fix for the problem mentioned here #81

OAuthenticator endpoint fix

---

src/components/Endpoint.tsx
src/components/HubLoginWidget.tsx
src/index.ts
style/stylesheets/home.css

This should resolve the authentication communication ticket. As always, open to suggestions :)

Authentication comms

---

globus_jupyterlab/handlers/api/transfer.py
globus_jupyterlab/login_manager.py
globus_jupyterlab/tests/api/test_transfer.py
globus_jupyterlab/tests/conftest.py
globus_jupyterlab/tests/integration/mini_resource_server.py

This PR adds unit tests and two bugs caught in the process. More info on each commit according to each fix.

Add tests and two bug-fixes for custom transfer submission

---

RELEASE.rst

@sturoscy-personal, added steps to RELEASE per your comment on #115, let me know if you see anything missing!

docs: Added RELEASE doc

---

.github/workflows/publish.yml

* Updates release workflow version
* Fixes 403 PyPi error due to extra `%`

Release workflow fixes
